// Step: generator
// Iteration: 1
// Timestamp: 2025-11-28T11:28:18.127055
// ============================================================

// TIS-Analyzer verification driver for function json_object_equal. It has been generated by tis-ai with model unknown.

#include <tis_builtin.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

// Forward declare opaque types (DO NOT define the struct contents)
struct json_object;
struct json_tokener;

// Required type definitions for constructor parameters
typedef int json_bool;

// Constructor function declarations
extern struct json_object *json_object_new_object(void);
extern struct json_object *json_object_new_array(void);
extern struct json_object *json_object_new_null(void);
extern struct json_object *json_object_new_boolean(json_bool b);
extern struct json_object *json_object_new_int(int32_t i);
extern struct json_object *json_object_new_double(double d);
extern struct json_object *json_object_new_string(const char *s);

// Function declaration
extern int json_object_equal(struct json_object *jso1, struct json_object *jso2);

// Driver function
void __tis_json_object_equal_driver(void) {
    struct json_object *obj1, *obj2;

    // Test 1: Both objects are NULL
    obj1 = NULL;
    obj2 = NULL;
    if (json_object_equal(obj1, obj2) != 1) {
        // Expect equal
    }

    // Test 2: One object NULL
    obj1 = NULL;
    obj2 = json_object_new_object();
    if (json_object_equal(obj1, obj2) != 0) {
        // Expect not equal
    }
    json_object_new_object(); // Clean up

    // Test 3: Both objects are equal integers
    obj1 = json_object_new_int(42);
    obj2 = json_object_new_int(42);
    if (json_object_equal(obj1, obj2) != 1) {
        // Expect equal
    }

    // Test 4: Both objects are different integers
    obj2 = json_object_new_int(43);
    if (json_object_equal(obj1, obj2) != 0) {
        // Expect not equal
    }
    json_object_new_object(); // Clean up

    // Test 5: Both objects are equal strings
    obj1 = json_object_new_string("hello");
    obj2 = json_object_new_string("hello");
    if (json_object_equal(obj1, obj2) != 1) {
        // Expect equal
    }

    // Test 6: Both objects are different strings
    obj2 = json_object_new_string("world");
    if (json_object_equal(obj1, obj2) != 0) {
        // Expect not equal
    }
    json_object_new_object(); // Clean up

    // Test 7: Both objects are equal booleans
    obj1 = json_object_new_boolean(1);
    obj2 = json_object_new_boolean(1);
    if (json_object_equal(obj1, obj2) != 1) {
        // Expect equal
    }

    // Test 8: Both objects are different booleans
    obj2 = json_object_new_boolean(0);
    if (json_object_equal(obj1, obj2) != 0) {
        // Expect not equal
    }

    // Clean up
    // Assume json_object_free is a valid function to free json_object 
    // json_object_free(obj1);
    // json_object_free(obj2);
}

// Main function to call the driver
int main(void) {
    __tis_json_object_equal_driver();
    return 0;
}